### PR TITLE
Mention that Doctrine will not pick up changes

### PR DESCRIPTION
**Pull request by roelvanduijnhoven**

### CODE REVIEW

**Comment by VasekPurchart** [comment]
Thanks for the PR, I agree completely, this is of course also one of the reasons why I created this repo.

Just a few formal things:
- Can you please reformat the code snippet so that it matches the first one? Use `modify`, which is more readable, add a comment saying at the end that no change will be propagated to DB.
-  There is a typo in `Moficiations` -> `modifications`.
- Start commit message with a lowercase letter please, as other commits do.

**Comment by roelvanduijnhoven** [comment]
Thanks for the input. I revised my PR.

**Comment by fprochazka** [comment]
:+1:

**Comment by VasekPurchart** [comment]
Merged manually in a single commit 5a7fd63. Thanks again.

**Pull request closed without merging**
